// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pragma_API.Models
{
    [Keyless]
    public partial class VCupomVenda
    {
        [Column("pedido")]
        public int? Pedido { get; set; }
        [Column("date", TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(511)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [Column("tipo_documento")]
        [StringLength(50)]
        [Unicode(false)]
        public string TipoDocumento { get; set; }
        [Required]
        [Column("documento")]
        [StringLength(255)]
        [Unicode(false)]
        public string Documento { get; set; }
        [Required]
        [Column("endereco")]
        [StringLength(1)]
        [Unicode(false)]
        public string Endereco { get; set; }
        [Required]
        [Column("bairo")]
        [StringLength(1)]
        [Unicode(false)]
        public string Bairo { get; set; }
        [Required]
        [Column("cep")]
        [StringLength(1)]
        [Unicode(false)]
        public string Cep { get; set; }
        [Required]
        [Column("cidade")]
        [StringLength(1)]
        [Unicode(false)]
        public string Cidade { get; set; }
        [Required]
        [Column("uf")]
        [StringLength(1)]
        [Unicode(false)]
        public string Uf { get; set; }
        [Required]
        [Column("email")]
        [StringLength(255)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [Column("ingresso_id")]
        [Unicode(false)]
        public int ingressoID { get; set; }
        [Required]
        [Column("nome_evento")]
        [Unicode(false)]
        public string nomeEvento { get; set; }
    }
}