// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pragma_API.Models
{
    [Keyless]
    public partial class VendaDB
    {
        [Column("Pedido")]
        public int Pedido { get; set; }

        [Column("EventoID")]
        public int EventoID { get; set; }

        [Column("NomeEvento")]
        public string NomeEvento { get; set; }
        [Column("CategoriaEvento")]
        public string CategoriaEvento { get; set; }

        [Column("DataTransacao", TypeName = "datetime")]
        public DateTime? DataTransacao { get; set; }

        [Column("QtdTotal")]
        public int QtdTotal { get; set; }

        [Column("ValorTransacao")]
        public decimal ValorTransacao { get; set; }

        [Column("NomeCliente")]
        public string NomeCliente { get; set; }
        
        [Column("Email")]
        public string Email { get; set; }

        [Column("TipoDocumento")]
        public string TipoDocumento { get; set; }
        
        [Column("Documento")]
        public string Documento { get; set; }
        
        [Column("Endereco")]
        public string Endereco { get; set; }
        
        [Column("Bairro")]
        public string Bairro { get; set; }
        
        [Column("Cep")]
        public string Cep { get; set; }
        
        [Column("Cidade")]
        public string Cidade { get; set; }
        
        [Column("Uf")]
        public string Uf { get; set; }

        [Column("Movimento")]
        public string Movimento { get; set; }

        [Column("DataShow", TypeName = "date")]
        public DateTime? DataShow { get; set; }

        [Column("Setor")]
        public string Setor { get; set; }

        [Column("NomePreco")]
        public string NomePreco { get; set; }

        [Column("QtdIngressos")]
        public int QtdIngressos { get; set; }

        [Column("ValorTotal")]
        public decimal ValorTotal { get; set; }

        [Column("ValorUnitario")]
        public decimal ValorUnitario { get; set; }

        [Column("TipoPreco")]
        public string TipoPreco { get; set; }

        [Column("PaginaAtual")]
        public int PaginaAtual { get; set; }

        [Column("QtdVendaPagina")]
        public int QtdVendaPagina { get; set; }

        [Column("TotalPaginas")]
        public int TotalPaginas { get; set; }

    }
}