// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pragma_API.Models
{
    [Keyless]
    public partial class VendaCupomItem
    {
       
        
        public int ingressoId { get; set; }

        public string nomeEvento { get; set; }
    }
}