// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pragma_API.Models
{
    [Keyless]
    public partial class VendaCupom
    {
       
        public int? Pedido { get; set; }
        
        public DateTime? Date { get; set; }
        public string Nome { get; set; }

        public string TipoDocumento { get; set; }
        
        public string Documento { get; set; }
        
        public string Endereco { get; set; }
        
        public string Bairo { get; set; }
        
        public string Cep { get; set; }
        
        public string Cidade { get; set; }
        
        public string Uf { get; set; }
        
        public string Email { get; set; }
        public List<VendaCupomItem> Itens { get; set; }
    }
}