// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Pragma_API.Models
{
    public partial class PragmaConciliaTMContext : DbContext
    {
        public PragmaConciliaTMContext()
        {
        }

        public PragmaConciliaTMContext(DbContextOptions<PragmaConciliaTMContext> options)
            : base(options)
        {
        }

        public virtual DbSet<VCupomVenda> VCupomVendas { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<VCupomVenda>(entity =>
            {
                entity.ToView("v_cupom_vendas");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}